<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"><title>Split string exactly in two parts — halveString • eatTools</title><script src="../deps/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"><link href="../deps/bootstrap-5.3.1/bootstrap.min.css" rel="stylesheet"><script src="../deps/bootstrap-5.3.1/bootstrap.bundle.min.js"></script><link href="../deps/font-awesome-6.5.2/css/all.min.css" rel="stylesheet"><link href="../deps/font-awesome-6.5.2/css/v4-shims.min.css" rel="stylesheet"><script src="../deps/headroom-0.11.0/headroom.min.js"></script><script src="../deps/headroom-0.11.0/jQuery.headroom.min.js"></script><script src="../deps/bootstrap-toc-1.0.1/bootstrap-toc.min.js"></script><script src="../deps/clipboard.js-2.0.11/clipboard.min.js"></script><script src="../deps/search-1.0.0/autocomplete.jquery.min.js"></script><script src="../deps/search-1.0.0/fuse.min.js"></script><script src="../deps/search-1.0.0/mark.min.js"></script><!-- pkgdown --><script src="../pkgdown.js"></script><meta property="og:title" content="Split string exactly in two parts — halveString"><meta name="description" content="strsplit splits a string according to a specific regular expression. The number
of occurrences of the splitting regular expression defines the number of splits. halveString
allows to split the string in only two parts, no matter how often the splitting regular expression occurs."><meta property="og:description" content="strsplit splits a string according to a specific regular expression. The number
of occurrences of the splitting regular expression defines the number of splits. halveString
allows to split the string in only two parts, no matter how often the splitting regular expression occurs."><meta property="og:image" content="https://weirichs.github.io/eatTools/logo.png"></head><body>
    <a href="#main" class="visually-hidden-focusable">Skip to contents</a>


    <nav class="navbar navbar-expand-lg fixed-top bg-light" data-bs-theme="light" aria-label="Site navigation"><div class="container">

    <a class="navbar-brand me-2" href="../index.html">eatTools</a>

    <small class="nav-text text-muted me-auto" data-bs-toggle="tooltip" data-bs-placement="bottom" title="">0.7.8.9000</small>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div id="navbar" class="collapse navbar-collapse ms-3">
      <ul class="navbar-nav me-auto"><li class="active nav-item"><a class="nav-link" href="../reference/index.html">Reference</a></li>
<li class="nav-item"><a class="nav-link" href="../news/index.html">Changelog</a></li>
      </ul><ul class="navbar-nav"><li class="nav-item"><form class="form-inline" role="search">
 <input class="form-control" type="search" name="search-input" id="search-input" autocomplete="off" aria-label="Search site" placeholder="Search for" data-search-index="../search.json"></form></li>
<li class="nav-item"><a class="external-link nav-link" href="https://github.com/weirichs/eatTools/" aria-label="GitHub"><span class="fa fab fa-github fa-lg"></span></a></li>
      </ul></div>


  </div>
</nav><div class="container template-reference-topic">
<div class="row">
  <main id="main" class="col-md-9"><div class="page-header">
      <img src="../logo.png" class="logo" alt=""><h1>Split string exactly in two parts</h1>

      <div class="d-none name"><code>halveString.rd</code></div>
    </div>

    <div class="ref-description section level2">
    <p><code>strsplit</code> splits a string according to a specific regular expression. The number
of occurrences of the splitting regular expression defines the number of splits. <code>halveString</code>
allows to split the string in only two parts, no matter how often the splitting regular expression occurs.</p>
    </div>

    <div class="section level2">
    <h2 id="ref-usage">Usage<a class="anchor" aria-label="anchor" href="#ref-usage"></a></h2>
    <div class="sourceCode"><pre class="sourceCode r"><code><span><span class="fu">halveString</span> <span class="op">(</span><span class="va">string</span>, <span class="va">pattern</span>, first <span class="op">=</span> <span class="cn">TRUE</span> , colnames<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="st">"X1"</span>, <span class="st">"X2"</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
    </div>

    <div class="section level2">
    <h2 id="arguments">Arguments<a class="anchor" aria-label="anchor" href="#arguments"></a></h2>
    <p></p>
<dl><dt id="arg-string">string<a class="anchor" aria-label="anchor" href="#arg-string"></a></dt>
<dd><p>A character vector.</p></dd>

  <dt id="arg-pattern">pattern<a class="anchor" aria-label="anchor" href="#arg-pattern"></a></dt>
<dd><p>character vector (or object which can be coerced to such) to use for splitting.</p></dd>

  <dt id="arg-first">first<a class="anchor" aria-label="anchor" href="#arg-first"></a></dt>
<dd><p>Logical: Relevant if the pattern occurs more than one time in the string. Defines whether
the first (default) or last occurrence is used for splitting.</p></dd>

  <dt id="arg-colnames">colnames<a class="anchor" aria-label="anchor" href="#arg-colnames"></a></dt>
<dd><p>Optional: character vector of length 2 to specify the colnames of the resulting data.frame.</p></dd>

</dl></div>
    <div class="section level2">
    <h2 id="value">Value<a class="anchor" aria-label="anchor" href="#value"></a></h2>
    <p>A matrix with two columns</p>
    </div>

    <div class="section level2">
    <h2 id="ref-examples">Examples<a class="anchor" aria-label="anchor" href="#ref-examples"></a></h2>
    <div class="sourceCode"><pre class="sourceCode r"><code><span class="r-in"><span><span class="va">str1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="st">"John_Bolton"</span>, <span class="st">"Richard_Milhouse_Nixon"</span>, <span class="st">"Madonna"</span><span class="op">)</span></span></span>
<span class="r-in"><span><span class="fu"><a href="https://rdrr.io/r/base/strsplit.html" class="external-link">strsplit</a></span><span class="op">(</span><span class="va">str1</span>, split <span class="op">=</span> <span class="st">"_"</span><span class="op">)</span></span></span>
<span class="r-out co"><span class="r-pr">#&gt;</span> [[1]]</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> [1] "John"   "Bolton"</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> [[2]]</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> [1] "Richard"  "Milhouse" "Nixon"   </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> [[3]]</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> [1] "Madonna"</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> </span>
<span class="r-in"><span><span class="fu">halveString</span><span class="op">(</span><span class="va">str1</span>, pattern <span class="op">=</span> <span class="st">"_"</span><span class="op">)</span></span></span>
<span class="r-out co"><span class="r-pr">#&gt;</span>      X1        X2              </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> [1,] "John"    "Bolton"        </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> [2,] "Richard" "Milhouse_Nixon"</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> [3,] "Madonna" NA              </span>
<span class="r-in"><span><span class="fu">halveString</span><span class="op">(</span><span class="va">str1</span>, pattern <span class="op">=</span> <span class="st">"_"</span>, first<span class="op">=</span><span class="cn">FALSE</span><span class="op">)</span></span></span>
<span class="r-out co"><span class="r-pr">#&gt;</span>      X1                 X2      </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> [1,] "John"             "Bolton"</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> [2,] "Richard_Milhouse" "Nixon" </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> [3,] "Madonna"          NA      </span>
<span class="r-in"><span></span></span>
<span class="r-in"><span><span class="co"># split patterns with more than one character and regular expression</span></span></span>
<span class="r-in"><span><span class="va">str2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="st">"John._.Bolton"</span>, <span class="st">"Richard._.Milhouse._.Nixon"</span>, <span class="st">"Madonna"</span><span class="op">)</span></span></span>
<span class="r-in"><span><span class="fu">halveString</span><span class="op">(</span><span class="va">str2</span>, pattern <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/encodeString.html" class="external-link">encodeString</a></span><span class="op">(</span><span class="st">"._."</span><span class="op">)</span>, first<span class="op">=</span><span class="cn">FALSE</span><span class="op">)</span></span></span>
<span class="r-out co"><span class="r-pr">#&gt;</span>      X1                   X2      </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> [1,] "John"               "Bolton"</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> [2,] "Richard._.Milhouse" "Nixon" </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> [3,] "Madonna"            NA      </span>
</code></pre></div>
    </div>
  </main><aside class="col-md-3"><nav id="toc" aria-label="Table of contents"><h2>On this page</h2>
    </nav></aside></div>


    <footer><div class="pkgdown-footer-left">
  <p>Developed by Sebastian Weirich, Martin Hecht, Karoline Sachse, Benjamin Becker, Nicole Mahler.</p>
</div>

<div class="pkgdown-footer-right">
  <p>Site built with <a href="https://pkgdown.r-lib.org/" class="external-link">pkgdown</a> 2.1.3.</p>
</div>

    </footer></div>





  </body></html>

